# from dp_capability_time_domain.models.currentloads import current_loads_level1
# from dp_capability_time_domain.models.waveloads import wave_loads_level1
# from dp_capability_time_domain.models.windloads import wind_loads_level1
from dp_capability_time_domain.standard import DYNAMIC_FACTOR_LEVEL1, environment